window.QUIZ_BANK = [
  {q:"How many teams play in the 2026 FIFA World Cup?",opts:["32","40","48","64"],ans:2,fact:"2026 is the first men's World Cup with 48 teams."},
  {q:"Which three countries host the 2026 World Cup?",opts:["USA, Canada and Mexico","Brazil, Argentina and Chile","Germany, France and Spain","UK, Ireland and France"],ans:0,fact:"The 2026 tournament is hosted by the USA, Canada and Mexico."},
  {q:"Which round comes immediately after the 2026 group stage?",opts:["Round of 16","Quarter-finals","Round of 32","Second group stage"],ans:2,fact:"The expanded 2026 format adds a Round of 32."},
  {q:"How many matches are in the 2026 World Cup?",opts:["64","80","96","104"],ans:3,fact:"The expanded 48-team tournament has 104 matches."},
  {q:"What is the maximum number of teams in a 2026 World Cup group?",opts:["3","4","5","6"],ans:1,fact:"The group stage uses 12 groups of 4 teams."},
  {q:"Which country hosted the opening match of the 1970 World Cup?",opts:["Brazil","Mexico","Italy","England"],ans:1,fact:"Mexico hosted the 1970 World Cup."},
  {q:"Who won the 2022 FIFA World Cup?",opts:["France","Brazil","Argentina","Croatia"],ans:2,fact:"Argentina won the 2022 World Cup in Qatar."},
  {q:"Who did Argentina beat in the 2022 final?",opts:["France","Germany","Netherlands","Morocco"],ans:0,fact:"Argentina beat France after a 3-3 draw and penalties."},
  {q:"Who won the Golden Boot at the 2022 World Cup?",opts:["Lionel Messi","Kylian Mbappe","Olivier Giroud","Julian Alvarez"],ans:1,fact:"Kylian Mbappe scored 8 goals in the 2022 tournament."},
  {q:"Which team finished fourth at the 2022 World Cup?",opts:["Morocco","Croatia","England","Portugal"],ans:0,fact:"Morocco became the first African team to reach a World Cup semi-final."},
  {q:"Who won the 2018 FIFA World Cup?",opts:["France","Croatia","Belgium","Germany"],ans:0,fact:"France won the 2018 tournament in Russia."},
  {q:"Who did France beat in the 2018 final?",opts:["Brazil","Croatia","Argentina","Belgium"],ans:1,fact:"France beat Croatia 4-2 in the 2018 final."},
  {q:"Who won the 2014 FIFA World Cup?",opts:["Argentina","Germany","Netherlands","Brazil"],ans:1,fact:"Germany won the 2014 World Cup in Brazil."},
  {q:"Who scored Germany's winning goal in the 2014 final?",opts:["Thomas Mueller","Mario Goetze","Miroslav Klose","Toni Kroos"],ans:1,fact:"Mario Goetze scored in extra time against Argentina."},
  {q:"Which country hosted the 2014 World Cup?",opts:["South Africa","Brazil","Russia","Germany"],ans:1,fact:"Brazil hosted the 2014 World Cup."},
  {q:"Who won the 2010 FIFA World Cup?",opts:["Netherlands","Spain","Germany","Uruguay"],ans:1,fact:"Spain won their first World Cup in 2010."},
  {q:"Who scored the winning goal in the 2010 final?",opts:["Xavi","David Villa","Andres Iniesta","Fernando Torres"],ans:2,fact:"Andres Iniesta scored the extra-time winner against the Netherlands."},
  {q:"Which country hosted the 2010 World Cup?",opts:["South Africa","Japan","Brazil","France"],ans:0,fact:"South Africa hosted Africa's first World Cup."},
  {q:"Who won the 2006 FIFA World Cup?",opts:["France","Italy","Germany","Portugal"],ans:1,fact:"Italy beat France on penalties in the 2006 final."},
  {q:"Which country hosted the 2006 World Cup?",opts:["Germany","Italy","France","Spain"],ans:0,fact:"Germany hosted the 2006 World Cup."},
  {q:"Who won the 2002 FIFA World Cup?",opts:["Germany","Brazil","Turkey","South Korea"],ans:1,fact:"Brazil won the 2002 tournament."},
  {q:"Which two countries co-hosted the 2002 World Cup?",opts:["Japan and South Korea","USA and Mexico","France and Belgium","Spain and Portugal"],ans:0,fact:"Japan and South Korea co-hosted in 2002."},
  {q:"Who won the 1998 FIFA World Cup?",opts:["Brazil","France","Italy","Croatia"],ans:1,fact:"France won the 1998 World Cup on home soil."},
  {q:"Who did France beat in the 1998 final?",opts:["Germany","Brazil","Argentina","Netherlands"],ans:1,fact:"France beat Brazil 3-0 in the 1998 final."},
  {q:"Who won the 1994 FIFA World Cup?",opts:["Italy","Brazil","Germany","Sweden"],ans:1,fact:"Brazil won the 1994 final on penalties."},
  {q:"Where was the 1994 World Cup held?",opts:["USA","Mexico","Italy","Spain"],ans:0,fact:"The United States hosted the 1994 World Cup."},
  {q:"Who won the 1990 FIFA World Cup?",opts:["Argentina","West Germany","Italy","England"],ans:1,fact:"West Germany beat Argentina in the 1990 final."},
  {q:"Which country hosted the 1990 World Cup?",opts:["Italy","Germany","Argentina","Mexico"],ans:0,fact:"Italy hosted the 1990 World Cup."},
  {q:"Who won the 1986 FIFA World Cup?",opts:["Brazil","Argentina","West Germany","France"],ans:1,fact:"Argentina won the 1986 tournament in Mexico."},
  {q:"Which player is famous for the 'Hand of God' goal?",opts:["Diego Maradona","Pele","Zinedine Zidane","Ronaldo"],ans:0,fact:"Diego Maradona scored that famous goal in 1986."},
  {q:"Who won the 1982 FIFA World Cup?",opts:["Brazil","Italy","West Germany","France"],ans:1,fact:"Italy won the 1982 World Cup in Spain."},
  {q:"Which country hosted the 1982 World Cup?",opts:["Argentina","Spain","Mexico","Italy"],ans:1,fact:"Spain hosted the 1982 tournament."},
  {q:"Who won the 1978 FIFA World Cup?",opts:["Netherlands","Argentina","Brazil","Italy"],ans:1,fact:"Argentina won the 1978 World Cup at home."},
  {q:"Who won the 1974 FIFA World Cup?",opts:["Netherlands","West Germany","Poland","Brazil"],ans:1,fact:"West Germany beat the Netherlands in the 1974 final."},
  {q:"Who won the 1970 FIFA World Cup?",opts:["Italy","Brazil","England","Uruguay"],ans:1,fact:"Brazil's 1970 team is one of football's most celebrated sides."},
  {q:"Which country hosted the 1970 World Cup?",opts:["Mexico","Chile","England","Brazil"],ans:0,fact:"Mexico hosted the 1970 tournament."},
  {q:"Who won the 1966 FIFA World Cup?",opts:["England","West Germany","Portugal","Soviet Union"],ans:0,fact:"England won the 1966 World Cup at Wembley."},
  {q:"Who scored a hat-trick in the 1966 World Cup final?",opts:["Bobby Charlton","Geoff Hurst","Eusebio","Franz Beckenbauer"],ans:1,fact:"Geoff Hurst scored three goals in the final."},
  {q:"Who won the 1962 FIFA World Cup?",opts:["Chile","Brazil","Czechoslovakia","Argentina"],ans:1,fact:"Brazil defended their title in 1962."},
  {q:"Who won the 1958 FIFA World Cup?",opts:["Sweden","Brazil","France","West Germany"],ans:1,fact:"Brazil won their first World Cup in 1958."},
  {q:"Which Brazilian legend was 17 during the 1958 World Cup?",opts:["Pele","Ronaldo","Romario","Zico"],ans:0,fact:"Pele starred for Brazil as a teenager in 1958."},
  {q:"Who won the 1954 FIFA World Cup?",opts:["Hungary","West Germany","Uruguay","Austria"],ans:1,fact:"West Germany's win over Hungary is known as the Miracle of Bern."},
  {q:"Who won the 1950 FIFA World Cup?",opts:["Brazil","Uruguay","Italy","Sweden"],ans:1,fact:"Uruguay won the decisive match against Brazil at the Maracana."},
  {q:"Who won the first FIFA World Cup in 1930?",opts:["Argentina","Uruguay","Brazil","Italy"],ans:1,fact:"Uruguay won the first World Cup in 1930."},
  {q:"Which country hosted the first FIFA World Cup?",opts:["Uruguay","Italy","France","Brazil"],ans:0,fact:"Uruguay hosted the first tournament in 1930."},
  {q:"Which country has won the most men's World Cups?",opts:["Germany","Italy","Brazil","Argentina"],ans:2,fact:"Brazil have won the men's World Cup five times."},
  {q:"Which two European countries have each won four men's World Cups?",opts:["Germany and Italy","France and Spain","England and Netherlands","Portugal and Belgium"],ans:0,fact:"Germany and Italy each have four men's World Cup titles."},
  {q:"Which country has played in every men's World Cup?",opts:["Germany","Brazil","Argentina","Italy"],ans:1,fact:"Brazil are the only team to appear in every men's World Cup."},
  {q:"Which player has scored the most goals in men's World Cup history?",opts:["Ronaldo","Miroslav Klose","Gerd Mueller","Lionel Messi"],ans:1,fact:"Miroslav Klose scored 16 World Cup goals."},
  {q:"Which country did Miroslav Klose represent?",opts:["Germany","Poland","Austria","Switzerland"],ans:0,fact:"Klose played for Germany."},
  {q:"Which player has the most men's World Cup appearances?",opts:["Cristiano Ronaldo","Lionel Messi","Lothar Matthaeus","Gianluigi Buffon"],ans:1,fact:"Lionel Messi reached 26 men's World Cup appearances in 2022."},
  {q:"Which goalkeeper won the Golden Glove in 2022?",opts:["Hugo Lloris","Emiliano Martinez","Dominik Livakovic","Yassine Bounou"],ans:1,fact:"Emiliano Martinez won the 2022 Golden Glove."},
  {q:"What is awarded to the tournament's top scorer?",opts:["Golden Ball","Golden Boot","Golden Glove","Golden Whistle"],ans:1,fact:"The Golden Boot goes to the top scorer."},
  {q:"What is awarded to the tournament's best player?",opts:["Golden Ball","Golden Boot","Golden Glove","Silver Cup"],ans:0,fact:"The Golden Ball is awarded to the best player."},
  {q:"What is awarded to the best goalkeeper?",opts:["Golden Boot","Golden Ball","Golden Glove","Golden Net"],ans:2,fact:"The Golden Glove recognizes the best goalkeeper."},
  {q:"How many players are on the pitch for one team at kickoff?",opts:["9","10","11","12"],ans:2,fact:"A football team starts with 11 players on the pitch."},
  {q:"How long is a standard football match before stoppage time?",opts:["60 minutes","80 minutes","90 minutes","100 minutes"],ans:2,fact:"A standard match is 90 minutes plus stoppage time."},
  {q:"How many halves are in a standard football match?",opts:["1","2","3","4"],ans:1,fact:"A standard match has two halves."},
  {q:"How long is each half in a standard match?",opts:["30 minutes","40 minutes","45 minutes","50 minutes"],ans:2,fact:"Each half is 45 minutes."},
  {q:"What happens in many knockout matches if the score is level after 90 minutes?",opts:["Replay next day","Extra time","Both teams advance","Coin toss"],ans:1,fact:"Knockout matches commonly go to extra time if level."},
  {q:"How long is football extra time?",opts:["10 minutes","20 minutes","30 minutes","45 minutes"],ans:2,fact:"Extra time is 30 minutes, split into two 15-minute halves."},
  {q:"What usually happens if a knockout match is level after extra time?",opts:["Penalties","Replay","Golden goal","Group points"],ans:0,fact:"Penalty shootouts decide many tied knockout matches."},
  {q:"How many players take the first round of kicks for each team in a penalty shootout?",opts:["3","4","5","6"],ans:2,fact:"Each team gets five initial penalty kicks."},
  {q:"What color card sends a player off?",opts:["Blue","Yellow","Red","Green"],ans:2,fact:"A red card means the player is sent off."},
  {q:"What does a yellow card usually mean?",opts:["A warning","A goal","A substitution","A corner"],ans:0,fact:"A yellow card is a caution."},
  {q:"What restart is awarded when the ball crosses the goal line last touched by the defending team?",opts:["Throw-in","Corner kick","Goal kick","Free kick"],ans:1,fact:"That situation gives the attacking team a corner."},
  {q:"What restart is awarded when the ball crosses the touchline?",opts:["Throw-in","Penalty","Corner","Kickoff"],ans:0,fact:"A throw-in restarts play from the touchline."},
  {q:"Which body part may an outfield player not deliberately use to control the ball?",opts:["Head","Foot","Chest","Hand"],ans:3,fact:"Outfield players cannot deliberately handle the ball."},
  {q:"Where does a match start from?",opts:["Corner arc","Center spot","Penalty spot","Goal area"],ans:1,fact:"Kickoff is taken from the center spot."},
  {q:"What is it called when a player scores three goals in one match?",opts:["Brace","Hat-trick","Clean sheet","Treble"],ans:1,fact:"Three goals by one player is a hat-trick."},
  {q:"What is it called when a goalkeeper concedes no goals?",opts:["Clean sheet","Hat-trick","Assist","Brace"],ans:0,fact:"A match with no goals conceded is a clean sheet."},
  {q:"What is an assist?",opts:["A saved shot","A pass leading to a goal","A yellow card","A missed penalty"],ans:1,fact:"An assist is the final pass or action before a goal."},
  {q:"What is a brace in football?",opts:["Two goals by one player","Two yellow cards for a team","Two saves","Two corners"],ans:0,fact:"A brace means two goals by one player."},
  {q:"Which position is allowed to use hands inside their own penalty area?",opts:["Striker","Midfielder","Goalkeeper","Winger"],ans:2,fact:"The goalkeeper can use hands inside their own penalty area."},
  {q:"What shape is the center mark area surrounded by?",opts:["Square","Circle","Triangle","Diamond"],ans:1,fact:"The center circle surrounds the center spot."},
  {q:"Which official runs along the touchline with a flag?",opts:["Referee","Assistant referee","Fourth official","VAR"],ans:1,fact:"Assistant referees use flags on the touchline."},
  {q:"What does VAR stand for?",opts:["Video Assistant Referee","Virtual Attack Rating","Verified Away Result","Visual Action Replay"],ans:0,fact:"VAR means Video Assistant Referee."},
  {q:"Which tournament uses national teams rather than clubs?",opts:["FIFA World Cup","UEFA Champions League","Premier League","Copa Libertadores"],ans:0,fact:"The FIFA World Cup is contested by national teams."},
  {q:"Which confederation includes most European national teams?",opts:["UEFA","CONMEBOL","AFC","CAF"],ans:0,fact:"UEFA is the European football confederation."},
  {q:"Which confederation includes South American national teams?",opts:["CAF","CONMEBOL","AFC","OFC"],ans:1,fact:"CONMEBOL is South America's football confederation."},
  {q:"Which confederation includes African national teams?",opts:["CAF","UEFA","CONCACAF","OFC"],ans:0,fact:"CAF is Africa's football confederation."},
  {q:"Which confederation includes many North and Central American teams?",opts:["AFC","CONCACAF","UEFA","CONMEBOL"],ans:1,fact:"CONCACAF covers North America, Central America and the Caribbean."},
  {q:"Which confederation includes many Asian national teams?",opts:["AFC","CAF","OFC","UEFA"],ans:0,fact:"AFC is the Asian Football Confederation."},
  {q:"Which country is known as La Albiceleste?",opts:["Argentina","Brazil","France","Spain"],ans:0,fact:"Argentina are nicknamed La Albiceleste."},
  {q:"Which country is known as Les Bleus?",opts:["Italy","France","Uruguay","Germany"],ans:1,fact:"France are nicknamed Les Bleus."},
  {q:"Which country is known as Die Mannschaft?",opts:["Germany","Netherlands","Austria","Switzerland"],ans:0,fact:"Die Mannschaft refers to Germany's national team."},
  {q:"Which country is known as the Selecao?",opts:["Portugal","Brazil","Spain","Mexico"],ans:1,fact:"Brazil are commonly called the Selecao."},
  {q:"Which country is known as the Three Lions?",opts:["England","Scotland","Wales","Ireland"],ans:0,fact:"England's national team is nicknamed the Three Lions."},
  {q:"Which country wears orange and is called Oranje?",opts:["Belgium","Netherlands","Denmark","Sweden"],ans:1,fact:"The Netherlands are famously known as Oranje."},
  {q:"Which country hosted the 2018 World Cup?",opts:["Qatar","Russia","Brazil","South Africa"],ans:1,fact:"Russia hosted the 2018 World Cup."},
  {q:"Which country hosted the 2022 World Cup?",opts:["Qatar","Japan","USA","Morocco"],ans:0,fact:"Qatar hosted the 2022 World Cup."},
  {q:"Which team did Croatia beat in the 2018 semi-final?",opts:["England","France","Brazil","Belgium"],ans:0,fact:"Croatia beat England after extra time in the 2018 semi-final."},
  {q:"Which team won the 2018 third-place match?",opts:["England","Belgium","Croatia","France"],ans:1,fact:"Belgium finished third in 2018."},
  {q:"Which team won the 2022 third-place match?",opts:["Morocco","Croatia","France","Netherlands"],ans:1,fact:"Croatia beat Morocco to finish third in 2022."},
  {q:"Which nation won Euro 2020, played in 2021?",opts:["England","Italy","Spain","Denmark"],ans:1,fact:"Italy won Euro 2020 at Wembley."},
  {q:"Which nation won the 2021 Copa America?",opts:["Brazil","Argentina","Chile","Uruguay"],ans:1,fact:"Argentina won the 2021 Copa America."},
  {q:"Which country did Lionel Messi captain to the 2022 World Cup title?",opts:["Argentina","Spain","Portugal","France"],ans:0,fact:"Messi captained Argentina to victory in 2022."},
  {q:"Which country did Cristiano Ronaldo first represent at a World Cup in 2006?",opts:["Brazil","Portugal","Spain","Italy"],ans:1,fact:"Cristiano Ronaldo represents Portugal."},
  {q:"Which country did Zinedine Zidane represent?",opts:["France","Italy","Algeria","Spain"],ans:0,fact:"Zidane was a star for France."},
  {q:"Which country did Ronaldo Nazario represent?",opts:["Portugal","Brazil","Argentina","Uruguay"],ans:1,fact:"Ronaldo Nazario was a Brazil striker."}
];
